---
title: "Figures for: Parasitism does not reduce thermal limits in the intermediate host of a Bopyrid isopod"
date: "`r Sys.Date()`"
output: 
  html_document:
          code_folding: hide
          code_download: true
          toc: true
          toc_float: true
  github_document:
          html_preview: false
          toc: true
          toc_depth: 3
---

```{r setup, include=T, message = F, warning = F, echo = F}
knitr::opts_chunk$set(
  echo = knitr::is_html_output(),
  fig.align = "center",
  fig.path = "../Figures/markdown/",
  dev = c("png", "pdf"),
  message = FALSE,
  warning = FALSE,
  collapse = T
)

theme_matt = function(base_size = 18,
                      dark_text = "grey20"){
  mid_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[2]
  light_text <-  monochromeR::generate_palette(dark_text, "go_lighter", n_colours = 5)[3]
  
  ggpubr::theme_pubr(base_family="sans") %+replace% 
    theme(
      panel.background  = element_rect(fill="transparent", colour=NA), 
      plot.background = element_rect(fill="transparent", colour=NA), 
      legend.background = element_rect(fill="transparent", colour=NA),
      legend.key = element_rect(fill="transparent", colour=NA),
      text = element_text(colour = mid_text, lineheight = 1.1),
      title = element_text(size = base_size * 1.5,
                           colour = dark_text),
      axis.text = element_text(size = base_size,
                               colour = mid_text),
      axis.title = element_text(size = base_size * 1.2,
                                margin = margin(0, 8, 0, 0)),
      legend.text = element_text(size=base_size * 0.9),
      legend.title = element_text(size = base_size * 0.9, 
                                  face = "bold"),
      plot.margin = margin(0.25, 0.25, 0.25, 0.25,"cm")
    )
}
```

# Main Figures

```{r eff-size, fig.width=8, fig.height=3}
bop_eff = dabest(full_data,
                 x = bopyrid,
                 y = ctmax, 
                 idx = c("no", "yes"),
                 paired = F)

bop_diff = mean_diff(bop_eff)

full_plot = plot(bop_diff, 
     rawplot.ylim = c(35.2, 37.6),
     rawplot.markersize = 4,
     rawplot.ylabel = "CTmax (°C)",
     palette = c("darkseagreen", "mediumpurple4"))

subset = full_data %>%  
  filter(ctmax > 36)  

sub_bop_eff = dabest(subset,
                 x = bopyrid,
                 y = ctmax, 
                 idx = c("no", "yes"),
                 paired = F)

sub_bop_diff = mean_diff(sub_bop_eff)

sub_plot = plot(sub_bop_diff, 
     rawplot.ylim = c(35.2, 37.6),
     rawplot.markersize = 4,
     rawplot.ylabel = "CTmax (°C)",
     palette = c("darkseagreen", "mediumpurple4"))

ggpubr::ggarrange(full_plot, sub_plot)
```

```{r lme-model}
iso.model = nlme::lme(data = full_data, 
                      fixed = ctmax ~ bopyrid, random = ~1|run)
kable(car::Anova(iso.model))
```

```{r sub-lme-model}
sub_iso.model = nlme::lme(data = subset, 
                      fixed = ctmax ~ bopyrid, random = ~1|run)
kable(car::Anova(sub_iso.model))
```

```{r forest-plot, fig.width=7, fig.height=7}
library(metafor)

effects = escalc(measure = "SMD",
       m2i = uninfected_mean,
       sd2i = uninfected_error,
       n2i = uninfected_N,
       m1i = infected_mean,
       sd1i = infected_error, 
       n1i = infected_N,
       slab = id,
       data = meta_data)

res <- rma(yi, vi, data=effects)

forest(res,
       header="Study")
```

# Supplementary Figures

```{r supp-fig-1, fig.width=8, fig.height=4}
temp_trace = ggplot(filter(temp_record, minute_passed < max(full_data$time) + 2), 
       aes(x = minute_passed, y = temp_C, group = factor(run))) + 
  geom_abline(slope = 0.3, 
              intercept = mean(temp_record[temp_record$minute_interval == 0, 8])) + 
  geom_abline(slope = 0.1, 
              intercept = mean(temp_record[temp_record$minute_interval == 0, 8])) + 
  geom_line(linewidth = 0.2, alpha = 0.8) + 
  geom_point(data = full_data, 
             aes(x = time, y = ctmax + 0.4),
             size = 2,
             shape = 25) +
  labs(x = "Time passed (minutes)",
       y = "Temperature (degrees C)",
       fill = "Trial Number") + 
  guides(colour = "none") + 
  theme_matt(base_size = 14) + 
  theme(legend.position = "right")


ramp_rates = ggplot(ramp_record, aes(x = minute_interval, y = ramp_per_minute, group = run)) + 
  geom_hline(yintercept = 0.3) + 
  geom_hline(yintercept = 0.1) + 
  geom_point(alpha = 0.5, colour = "grey") + 
  geom_smooth(linewidth = 2, colour = "black") + 
  ylim(0,0.4) + 
  labs(y = "Ramp Rate (deg. C / min.)",
       x = "Time into run (minute)") + 
  theme_matt(base_size = 14)

ggpubr::ggarrange(temp_trace, ramp_rates, labels = "AUTO")
```

```{r include = F}
run_start = temp_record %>% 
  group_by(run) %>% 
  arrange(time_point) %>% 
  filter(time_point< 50) %>% 
  summarise(start_temp = mean(temp_C))

run_limits = full_data %>% 
  group_by(run, bopyrid) %>% 
  summarise(mean_lim = mean(ctmax))

inner_join(run_start, run_limits, by = c("run")) %>% 
  ggplot(aes(x = start_temp, y = mean_lim)) + 
  geom_point()
```
